### ISSUE TITLE
"AthenaLauncher" directory would be better called "Athena Launcher"

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/pantheon-launcher#10]
I.e., with a space. Other apps' AppData directories include spaces, e.g. "Blender Foundation".

**Comment by two-one-five** [comment]
I suppose it creates less problems later though wherever possible because I think some command lines/OS environments consider spaces in directories to be unbecoming. So I'm not sure.

**Comment by ctrlaltdavid** [comment]
I think spaces in file names are OK these days. Except maybe in arcane build tools, which is why I have paths in my build workspaces not have spaces, though that's really just from habit rather than any known need to.

**Comment by two-one-five** [comment]
This has been completed with the latest pre-release of the launcher (v0.0.1q)
