### ISSUE TITLE
Launcher breaks "drag&drop" functionality

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/pantheon-launcher#16]
Normally, you can drag file onto the interface window and it will be processed accordingly, i.e. *.json will be loaded, *.fst equips avatar etc.
if interface is started through the launcher, this no longer works, cursor shows a :no_entry_sign: instead of the usual "COPY +"

**Comment by two-one-five** [comment]
I do believe I reproduced this before. I will have to look in to how drag and drop works for the Interface, perhaps the launcher can proxy through the drops.

**Comment by two-one-five** [comment]
This has been fixed with the launcher using detached launching by default.
