### ISSUE TITLE
Launcher steals focus in SteamVR desktop

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/pantheon-launcher#17]
when using steamVR desktop, if you give focus to (click on) the launcher window, it "steals" focus and no other desktop windows or programs can be used until you ALT-TAB to another program/window.

the launcher itself can not be operated through steamVR desktop.

**Comment by two-one-five** [comment]
I do not have my VR gear at the moment, but I recall using SteamVR's desktop view while I had it and it had worked just fine. Perhaps you are using some custom settings/configs for SteamVR that is causing the weirdness to conflict?

Does this still happen?

**Comment by two-one-five** [comment]
I've observed this happening to me, not entirely sure why.
