### ISSUE TITLE
Unable to close launcher without task manager.

### ISSUE THREAD

**Issue by Aitolda** [vircadia/pantheon-launcher#18]
Just like it sounds.  Pressing the X at thet top right yields no result.  Launcher remains open and responsive otherwise. Restarting Launcher yields the same result. Rebooting machine and restarting same result.

Version 0.01h

**Comment by two-one-five** [comment]
Is this still happening? No one else has reported this yet so it may have been a one off.

**Comment by two-one-five** [comment]
Closing for now, will re-open/maybe someone can make a new issue if this happens again to them.
