### ISSUE TITLE
VircadiaLauncher Directory would be better called Vircadia Launcher

### ISSUE THREAD

**Issue by 1st-BrainStormer** [vircadia/pantheon-launcher#20]
in App Data it is VircadiaLauncher and in program files its Vircadia  Launcher.  These should match each other.

**Comment by two-one-five** [comment]
This has been completed and deployed with release v0.0.1q, the old directory will still exist and the installs will not be migrated (I wrote functions but it's just more trouble needing admin... etc., I will setup further control and functionality for the launcher to handle itself over time though so if we need to migrate to a new directory later, I can automate it.)
