### ISSUE TITLE
Download button doesn't work properly if installs folder isn't set

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/pantheon-launcher#9]
Repro:
- Delete all launcher JSONs.
- Run launcher.
- Press "download" button.
- You are prompted to select a directory.
- Select directory.
- "download" button is still grey as if downloading but no download is happening (log messages aren't being output to command window). Clicking "download" button asks if you want to cancel the download.

Or maybe I didn't wait long enough for the download to start??

**Comment by two-one-five** [comment]
Fix has been applied to a commit for the linked PR.
